### PR TITLE
Add PHI-Canto species lists

### LINKED ISSUE #10: Add lists of PHI-Canto pathogen and host species
Required for moving forward with PHI-Canto roll out and manuscript preparation.

### PR DESCRIPTION
**Pull request by jseager7**
Fixes #10

This pull request adds the pathogen and host species lists that are used in PHI-Canto. Previously they were stored in a private repository, which meant they couldn't be referenced. I've renamed and reordered the columns to be more conventional and I've added a readme file explaining the columns and the data.

### CODE REVIEW

**Comment by jseager7** [comment]
@CuzickA Could you please check through the files linked below and let me know if there are any problems?

I was wondering whether I should add more common names, particularly to the host species list, because I suspect there are some that we've missed.

Readme:
https://github.com/PHI-base/data/blob/phicanto-species/species/README.md

Pathogen species:
https://github.com/PHI-base/data/blob/phicanto-species/species/phicanto_pathogen_species.csv

Host species:
https://github.com/PHI-base/data/blob/phicanto-species/species/phicanto_host_species.csv

**Comment by CuzickA** [comment]
Thanks @jseager7 I think we have only used the common names when NCBI Taxonomy has a common name recorded. Do you think we have missed some?

The latest PHI4.12 release has a larger number of pathogen and host species than the current PHI-Canto lists. These additional species will probably need adding to the PHI-Canto lists and loading into PHI-Canto.
image

**Comment by jseager7** [comment]
> I think we have only used the common names when NCBI Taxonomy has a common name recorded. Do you think we have missed some?

Now that I've bothered to double check, it seems that the only hosts without common names also don't have names in NCBI Taxonomy. So we shouldn't have missed any.

Does PHI-base always try to follow the NCBI Taxonomy nomenclature? If so, I should update the readme to explain that.

> The latest PHI4.12 release has a larger number of pathogen and host species than the current PHI-Canto lists. These additional species will probably need adding to the PHI-Canto lists and loading into PHI-Canto.

Do you want me to update the list with the 4.12 species before merging these changes?

**Comment by CuzickA** [comment]
> Does PHI-base always try to follow the NCBI Taxonomy nomenclature? If so, I should update the readme to explain that.

Yes, possibly with a rare couple of exceptions. 

> Do you want me to update the list with the 4.12 species before merging these changes?

Yes please. I think it would be good to keep the lists as up-to-date as possible.

**Comment by jseager7** [comment]
@CuzickA I've updated the species lists with the latest species from PHI-base v4.12. The only rows I've excluded are ones containing a genus instead of a species (_Rattus_, _Citrus_, etc.)

I still need to load the species into Canto, but these changes could be merged before that if necessary.

**Comment by jseager7** [comment]
The species lists have been updated on PHI-Canto now, so I'm merging this.

**Pull request merged**
